sudo: required
services:
  - docker
language: python
python:
  - "3.5"
script:
  - sh .travis/deploy_dockerhub.sh
after_success:
  - sh .travis/deploy_heroku.sh
notifications:
    slack: SLACK-USERNAME:SLACK-TOKEN
